pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        // Google Maven 必须第一顺位，Media3仅在此仓库分发
        google()
        mavenCentral()
    }
}
rootProject.name = "1"
include ':app'
