plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace "com.tvlive"
    compileSdk 34

    defaultConfig {
        applicationId "com.tvlive"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

   signingConfigs {
    release {
        // 👇 这行是修复关键：从项目根目录读取密钥，不再报错
        storeFile rootProject.file("release.keystore")
        storePassword System.getenv("STORE_PASSWORD")
        keyAlias System.getenv("KEY_ALIAS")
        keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    // 关闭所有可能报错的功能
    viewBinding { enabled = false }
    buildFeatures { dataBinding = false }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // 播放器
    implementation "com.google.android.exoplayer:exoplayer:2.19.1"
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
